# Generated by Django 6.1 on 2026-08-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_guest_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
